version: "3"

services:
  client:
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    volumes:
      - ./client:/app
    restart: always
  authorization_server:
    tty: true
    build:
      context: ./authorizationServer
      dockerfile: Dockerfile
    ports:
      - 10001:10001
    volumes:
      - ./authorizationServer:/app
    restart: always
  protected_resource:
    tty: true
    build:
      context: ./protectedResource
      dockerfile: Dockerfile
    ports:
      - 10002:10002
    volumes:
      - ./protectedResource:/app
    restart: always