version: "3"

services:
  oauth:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - .:/app
    restart: always